// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Сервис баннеров
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */
package main

import (
	"log"
	"net/http"
	

	op "github.com/iaPlotnikovv/New-breath/generated/go"
	serv "github.com/iaPlotnikovv/New-breath/server"
    "context"
	"github.com/iaPlotnikovv/New-breath/pkg/storage"
)

	
 func main() {
	_, cancel := context.WithCancel(context.Background())
	defer cancel()

	 log.Printf("Server started")

	 db := storage.InitDB()
	 defer db.Close()

	
	 APIService := serv.NewBannerService(db)
	 APIController := op.NewDefaultAPIController(APIService)
	 router := op.NewRouter(APIController)
 
	 log.Fatal(http.ListenAndServe(":8080", router))
 }
 